### ISSUE TITLE
Change the scrollbar to MUI's scrollbar.

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/guidefox#402]
Change the scrollbar. I think the one used here is the browser's default scrolbar. Change it to MUI scrollbar

![image](https://github.com/user-attachments/assets/80125d1a-827b-41a4-a089-ed29c3581445)

**Comment by MandeepPaul** [comment]
Do I need to style the scrollbar globally across our app?

### This is the current one on chrome browser
![image](https://github.com/user-attachments/assets/a2abe637-7416-4b87-8d4e-3f6b764f0868)

**Comment by erenfn** [comment]
Yes

**Comment by MandeepPaul** [comment]
Is this better?

![image](https://github.com/user-attachments/assets/0eb947cb-1be1-47c7-b3b8-fc327b842720)

**Comment by erenfn** [comment]
@gorkem-bwl

**Comment by gorkem-bwl** [comment]
Yes, way better. Thanks.
