### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by Yup03** [bluewave-labs/guidefox#444]
Error is thrown when I follow the instructions from the README file
1. When I run `sudo certbot --nginx`
2. An error pops up from the terminal saying like '_**error while running nginx -c /etc/nginx/nginx.conf -t**_' basically meaning that there is something wrong with the configuration file and I think this syntax here coming from the **README** might be a little bit off

![image](https://github.com/user-attachments/assets/e3f04dba-8900-49af-8f17-d6484d4117c7)

**Comment by erenfn** [comment]
Thanks for pointing it out. The first line accidentally got commented out. There should be `server {` before `listen 80`

**Comment by Yup03** [comment]
I'm glad I could help, I kinda notice that the syntax was actually correct in the **README** file but was only cut out on **preview mode**  
And as you're saying that's due to the fact it was commented out
